module.exports = {
  FETCH_DEVICE_ID_REQUEST: 'FETCH_DEVICE_ID_REQUEST',
  FETCH_DEVICE_ID_SUCCESS: 'FETCH_DEVICE_ID_SUCCESS',
  FETCH_DEVICE_ID_FAILURE: 'FETCH_DEVICE_ID_FAILURE',

  CHANGE_DEPARTMENT_REQUEST: 'CHANGE_DEPARTMENT_REQUEST',
  CHANGE_DEPARTMENT_SUCCESS: 'CHANGE_DEPARTMENT_SUCCESS',
  CHANGE_DEPARTMENT_FAILURE: 'CHANGE_DEPARTMENT_FAILURE',

  CHANGE_TEAM_REQUEST: 'CHANGE_TEAM_REQUEST',
  CHANGE_TEAM_SUCCESS: 'CHANGE_TEAM_SUCCESS',
  CHANGE_TEAM_FAILURE: 'CHANGE_TEAM_FAILURE',
}
